apiVersion: v2
name: kafka
description: The home server kafka helm chart
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kafka
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 26.8.5
