apiVersion: v2
name: kafka
description: The home server kafka helm chart
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: 26.8.5
