kafka:
  name: kafka
  configmap_name: kafka-config
  cert_issuer: kafka-selfsigned-issuer
  volumes:
    data: kafka-data-volume
    certs: kafka-certs-volume
    keystores: kafka-keystores-volume
  secrets:
    super_user: kafka-superuser
    controller_user: kafka-controller-user
    broker_user: kafka-broker-user
    certificate: kafka-certificate
  networking:
    internal_port: 9094
    public_port: 30020
kafkaui:
  name: kafka-ui
  networking:
    internal_port: 8080