kafka:
  name: kafka
  version: 3.6.1
  configmap:
    primary: kafka-config
  cert_issuer: kafka-selfsigned-issuer
  volumes:
    data: kafka-data-volume
    certs: kafka-certs-volume
    keystores: kafka-keystores-volume
  secrets:
    super_user: kafka-superuser
    controller_user: kafka-controller-user
    broker_user: kafka-broker-user
    certificate: kafka-certificate
    keystore_password: kafka-keystore-password
  networking:
    services:
      private: kafka-private-service
      public: kafka-public-service
    internal_port: 9092
    controller_port: 9093
    external_port: 9094
    public_port: 30020
    lan_ip: 192.168.7.232
kafka_ui:
  name: kafka-ui
  version: v0.7.1
  configmap:
    primary: kafka-ui-config
    dynamic_config: kafka-ui-dynamic-config
  networking:
    services:
      private: kafka-ui-private-service
    internal_port: 8080
  volumes:
    config: config-volume
    dynamic_config_raw: dynamic-config-raw-volume
  cert_issuer: letsencrypt-kafka-ui
  ingress:
    name: kafka-ui-ingress
    host: kafka.craigmiller160.us
    ipWhitelist: 47.196.38.229/32
  secrets:
    certificate: letsencrypt-kafka-ui-private-key