apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafka_ui.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kafka_ui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka_ui.name }}
    spec:
      initContainers:
        - name: {{ .Values.kafka_ui.name }}-config-modifier
          image: busybox:1.35.0
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              cp /etc/kafkaui_raw/dynamic-config.yaml /etc/kafkaui &&
              sed -i 's/\$SUPER_USER/${KAFKA_SUPER_USER_NAME}/g' /etc/kafkaui/dynamic-config.yaml
          env:
            - name: KAFKA_SUPER_USER_NAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.kafka.secrets.super_user }}
            - name: KAFKA_SUPER_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.kafka.secrets.super_user }}
          volumeMounts:
            - mountPath: /etc/kafkaui
              name: {{ .Values.kafka_ui.volumes.dynamic_config }}
            - mountPath: /etc/kafkaui_raw
              name: {{ .Values.kafka_ui.volumes.dynamic_config_raw }}
      containers:
        - name: {{ .Values.kafka_ui.name }}
          image: "provectuslabs/kafka-ui:{{ .Values.kafka_ui.version }}"
          ports:
            - containerPort: {{ .Values.kafka_ui.networking.internal_port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.kafka_ui.configmap.primary }}
          volumeMounts:
            - mountPath: /etc/kafkaui
              name:  {{ .Values.kafka_ui.volumes.dynamic_config }}
      volumes:
        - name: {{ .Values.kafka_ui.volumes.dynamic_config_raw }}
          configMap:
            name: {{ .Values.kafka_ui.configmap.dynamic_config }}
        - name: {{ .Values.kafka_ui.volumes.dynamic_config }}
          emptyDir: {}