apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafka.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kafka.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.name }}
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.5.2-0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.kafka.networking.internal_port }}