apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kafka_ui.configmap.dynamic_config }}
data:
  dynamic-config.yaml: |
    kafka:
      clusters:
      - bootstrapServers: "{{ .Values.kafka.networking.services.private }}:{{ .Values.kafka.networking.internal_port }}"
        name: SuperUserKafka
        properties:
          security.protocol: SASL_PLAINTEXT
          sasl.mechanism: PLAIN
          sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required
            username="user" password="password";
        readOnly: false
