apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka_ui.networking.services.private }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.kafka_ui.name }}
  ports:
    - port: {{ .Values.kafka_ui.networking.internal_port }}
      targetPort: {{ .Values.kafka_ui.networking.internal_port }}