apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafka_ui.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kafka_ui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka_ui.name }}
    spec:
      containers:
        - name: {{ .Values.kafka_ui.name }}
          image: "provectuslabs/kafka-ui:{{ .Values.kafka_ui.version }}"
          ports:
            - containerPort: {{ .Values.kafka_ui.networking.internal_port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.kafka_ui.configmap_name }}