apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.kafka.name }}
  ports:
    - port: {{ .Values.kafka.networking.internal_port }}
      targetPort: {{ .Values.kafka.networking.internal_port }}
      nodePort: {{ .Values.kafka.networking.public_port }}