apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.kafka.cert_issuer }}
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.kafka.secrets.certificate }}
spec:
  isCA: true
  commonName: {{ .Values.kafka.secrets.certificate }}
  secretName: {{ .Values.kafka.secrets.certificate }}
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: {{ .Values.kafka.cert_issuer }}
    kind: ClusterIssuer
    group: cert-manager.io