apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kafkaui.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.kafkaui.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafkaui.name }}