apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - port: {{ .Values.networking.internal_port }}
      targetPort: {{ .Values.networking.internal_port }}
      nodePort: {{ .Values.networking.public_port }}