apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.kafka.cert_issuer }}
spec:
  selfSigned: {}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kafka.secrets.keystore_password }}
data:
  # Password is "password1@", exclusively internal and does not need to be secure
  password: "{{ "password1@" | b64enc }}"
type: Opaque

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.kafka.secrets.certificate }}
spec:
  isCA: true
  commonName: {{ .Values.kafka.secrets.certificate }}
  secretName: {{ .Values.kafka.secrets.certificate }}
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: {{ .Values.kafka.cert_issuer }}
    kind: ClusterIssuer
    group: cert-manager.io
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        name: {{ .Values.kafka.secrets.keystore_password }}
        key: password