apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.kafka.data_volume_name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: craig-hostpath
  resources:
    requests:
      storage: 5Gi