apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.networking.services.public }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.kafka.name }}
  ports:
    - port: {{ .Values.kafka.networking.external_port }}
      targetPort: {{ .Values.kafka.networking.external_port }}
      nodePort: {{ .Values.kafka.networking.public_port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kafka.networking.services.private }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.kafka.name }}
  ports:
    - name: internal
      port: {{ .Values.kafka.networking.internal_port }}
      targetPort: {{ .Values.kafka.networking.internal_port }}
    - name: controller
      port: {{ .Values.kafka.networking.controller_port }}
      targetPort: {{ .Values.kafka.networking.controller_port }}